const types = {
    TOGGLE_ISLOGIN: 'TOGGLE_ISLOGIN',
    TOGGLE_SHOW_LOGIN: 'TOGGLE_SHOW_LOGIN',
    TOGGLE_SHOW_REGISTER: 'TOGGLE_SHOW_REGISTER',
    TOGGLE_SHOW_MODAL: 'TOGGLE_SHOW_MODAL',
    EDIT_USER_NAME: 'EDIT_USER_NAME', // 编辑简历中的姓名
    EDIT_USER_DESC: 'EDIT_USER_DESC', // 编辑简历中的介绍
    SET_USER_NAME: 'SET_USER_NAME',
    SET_RESUME_EDUCATION_INFO: 'SET_RESUME_EDUCATION_INFO', // 教育经历
    SET_RESUME_SELF_VAL: 'SET_RESUME_SELF_VAL', // 个人评价
    SET_RESUME_TARGET: 'SET_RESUME_TARGET', // 求职目标
    SET_RESUME_EXTRA: 'SET_RESUME_EXTRA', // 自定义模块
    SET_RESUME_USERINFOO: 'SET_RESUME_USERINFOO', // 整体设定
    SET_RESUME_EXPERIENCE: 'SET_RESUME_EXPERIENCE', // 项目经验
    SET_RESUME_ITEM: 'SET_RESUME_ITEM' // 对传入的项进行更改
};

export default types;
