const types = {
    TOGGLE_ISLOGIN: 'TOGGLE_ISLOGIN',
    TOGGLE_SHOW_LOGIN: 'TOGGLE_SHOW_LOGIN',
    TOGGLE_SHOW_REGISTER: 'TOGGLE_SHOW_REGISTER',
    TOGGLE_SHOW_MODAL: 'TOGGLE_SHOW_MODAL',
    EDIT_USER_NAME: 'EDIT_USER_NAME', // 编辑简历中的姓名
    EDIT_USER_DESC: 'EDIT_USER_DESC', // 编辑简历中的介绍
    SET_USER_NAME: 'SET_USER_NAME'
};

export default types;
