const types = {
    TOGGLE_ISLOGIN: 'TOGGLE_ISLOGIN',
    TOGGLE_SHOW_LOGIN: 'TOGGLE_SHOW_LOGIN',
    TOGGLE_SHOW_REGISTER: 'TOGGLE_SHOW_REGISTER',
    TOGGLE_SHOW_MODAL: 'TOGGLE_SHOW_MODAL',
    SET_USER_NAME: 'SET_USER_NAME'
};

export default types;
